### ISSUE TITLE
Helm deployment problem

### ISSUE THREAD

**Issue by tropnikovvl** [pbchekin/vault-sync#13]
In my deployment, I do not specify secrets as `environment variables`, but add them through the default `vaultSync` parameters 

```yaml
vaultSync:
  id: vault-sync
  full_sync_interval: 60
  bind: 0.0.0.0:8202
  src:
    url: http://vault-1.vault.svc.cluster.local:8200/
    prefix: ""
    backend: my-backend
    version: 2
    role_id: 7726aexxxx
    secret_id: 48bccb4xxxx
  dst:
    url: http://vault-2.vault.svc.cluster.local:8200/
    prefix: ""
    backend: my-backend
    version: 2
    token: hvs.yxxxx
```

and,as a result, get a deployment error, since already [existing](https://github.com/pbchekin/vault-sync/blob/main/install/helm/vault-sync/values.yaml#L24C1-L30C33) environment variables break the application. 

```yaml
secrets:
  VAULT_SYNC_SRC_TOKEN: eHh4
#  VAULT_SYNC_SRC_ROLE_ID: xxx
#  VAULT_SYNC_SRC_SECRET_ID: xxx
  VAULT_SYNC_DST_TOKEN: eHh4
#  VAULT_SYNC_DST_ROLE_ID: xxx
#  VAULT_SYNC_DST_SECRET_ID: xxx
```

After all, they contain invalid data
