### ISSUE TITLE
Allow for self managed secrets

### ISSUE THREAD

**Issue by micxba** [pbchekin/vault-sync#29]
Currently you need to specify sensitive data in the HELM values file, I made an update to the chart which should resolve that where you can specify your own secret. I don't have contributor access so here is how you can easily implement this:

values.yaml
```yaml
secrets:
  externalSecretName: ""  # leave blank to use inline values and create vault-sync
  values:
    # Secrets must be base64 encoded
    # To use Vault app roles set token values to null
    VAULT_SYNC_SRC_TOKEN:
      value: eHh4
    # VAULT_SYNC_SRC_ROLE_ID:
    #   value: xxx
    # VAULT_SYNC_SRC_SECRET_ID:
    #   value: xxx
    VAULT_SYNC_DST_TOKEN: 
      value: eHh4
    # VAULT_SYNC_DST_ROLE_ID:
    #   value: xxx
    # VAULT_SYNC_DST_SECRET_ID:
    #   value: xxx
```

secret.yaml
```yaml
{{- if not .Values.secrets.externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-sync.fullname" . }}
  labels:
    {{- include "vault-sync.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $entry := .Values.secrets.values }}
  {{ $key }}: {{ $entry.value | quote }}
  {{- end }}
{{- end }}
```

deployment.yaml
```yaml
  env:
    - name: RUST_LOG
      value: info
  {{- if not .Values.secrets.externalSecretName }}
    {{- range $key, $_ := .Values.secrets.values }}
    - name: {{ $key }}
      valueFrom:
        secretKeyRef:
          name: vault-sync
          key: {{ $key }}
    {{- end }}
  {{- end }}
  {{- if .Values.secrets.externalSecretName }}
  envFrom:
    - secretRef:
        name: {{ .Values.secrets.externalSecretName }}
  {{- end }}
```
